Porting python implementation to ruby
heremaps/flexible-polyline pull request #58
Opened 2022-08-26 20:49 UTC by ProGM

Hi there,

This is a porting of the python implementation in Ruby. I need this library for our company projects in Ruby on Rails 💎 

I hope you'll decide to merge this ;)

Implementation details:
* Supports ruby 2.7+
* It's [ready to be released on rubygems.org](https://github.com/monade/flexible-polyline/blob/feature/ruby-implementation/ruby/flexpolyline.gemspec)
* Tests use made with rspec, implementing the same suite of Python (runnable via `bundle exec rspec`)
* Documentation using Yard (runnable via `bundle exec yardoc`)
* It's configured with rubocop for code linting

2023-01-20 22:35 UTC, sergykorets commented
Please merge

2023-01-23 11:49 UTC, roshats requested changes

2023-01-23 11:49 UTC, roshats commented on ruby/spec/spec_helper.rb
> +# Dir[File.expand_path('support/*.rb', __dir__)].each { |f| require f }
This code is not needed. Please remove it.

2023-01-23 11:49 UTC, roshats commented on ruby/flexpolyline.gemspec
> +  s.add_dependency 'activesupport', ['>= 5', '< 8']
Please do not depend on `activesupport`.

2023-02-16 10:19 UTC, ProGM commented
@roshats Hi, I've made all the requested changes. Let me know if it's all fine or it's ready to be merged :)

2023-02-20 08:04 UTC, roshats commented
Thanks @ProGM .

@VeaaC , I think me can merge this Pull Request and publish ruby gem.

2023-02-20 08:09 UTC, roshats approved these changes

2023-02-20 08:10 UTC, VeaaC commented
@ProGM the commits needs to be signed, then I can go ahead an merge ( https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification )

2023-02-20 19:50 UTC, ProGM commented
@VeaaC @roshats Commits signed ;)

2023-02-21 08:13 UTC, VeaaC commented
Merging. @roshats  / @ProGM  can you also add some CI to test against the shared conversion tests in https://github.com/heremaps/flexible-polyline/tree/master/test ?

2023-02-21 08:13 UTC, merged